name: GitHub Actions  to publish Docker Image
run-name: ${{ github.actor }} in actionðŸš€
on: 
  push :
    branches :
      - main
jobs:
  Build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build and tag docker image
        run : 
          docker build -t ${{secrets.USERNAME}}/uas-pcc-tovikn-2024:latest -f Dockerfile . 
      - name : push to Dockerhub  
        run  : docker login -u ${{secrets.USERNAME}} -p ${{secrets.ACCESS_TOKEN}} && docker push ${{secrets.USERNAME}} && ${{secrets.USERNAME}}/uas-pcc-tovikn-2024:latest